### ISSUE TITLE
sometimes got deadlock error

### ISSUE THREAD

**Issue by di3663** [garyburd/redigo#287]
```
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [IO wait]:
internal/poll.runtime_pollWait(0xc24fd0, 0x72, 0x0)
        /go/src/runtime/netpoll.go:173 +0x4b
internal/poll.(*pollDesc).wait(0x12b88204, 0x72, 0x869100, 0x0, 0x0)
        /go/src/internal/poll/fd_poll_runtime.go:85 +0x8c
internal/poll.(*ioSrv).ExecIO(0x89c6a4, 0x12b88154, 0x71397c, 0x12b881ac, 0x0, 0x0)
        /go/src/internal/poll/fd_windows.go:195 +0xf1
internal/poll.(*FD).Read(0x12b88140, 0x12bdc000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /go/src/internal/poll/fd_windows.go:439 +0x1f0
net.(*netFD).Read(0x12b88140, 0x12bdc000, 0x1000, 0x1000, 0x0, 0x0, 0x4bd431)
        /go/src/net/fd_windows.go:151 +0x3f
net.(*conn).Read(0x12b04788, 0x12bdc000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /go/src/net/net.go:176 +0x56
bufio.(*Reader).fill(0x12b683c0)
        /go/src/bufio/bufio.go:97 +0xe6
bufio.(*Reader).ReadSlice(0x12b683c0, 0xa, 0x0, 0x5120cf, 0x12b88140, 0x12bcf000, 0x2d)
        /go/src/bufio/bufio.go:338 +0x23
github.com/garyburd/redigo/redis.(*conn).readLine(0x12b7c200, 0x657215, 0x520ad6, 0x12b88140, 0x12bcf000, 0x2d)
        /user/.GoPath/src/github.com/garyburd/redigo/redis/conn.go:407 +0x2d
github.com/garyburd/redigo/redis.(*conn).readReply(0x12b7c200, 0x0, 0x0, 0x12be2880, 0x1)
        /user/.GoPath/src/github.com/garyburd/redigo/redis/conn.go:480 +0x25
github.com/garyburd/redigo/redis.(*conn).Do(0x12b7c200, 0x6facd8, 0x6, 0x12be2880, 0x1, 0x1, 0x40f7b5, 0x1d40b8, 0x60, 0x0)
```

**Comment by garyburd** [comment]
Run the application with the [race detector](https://golang.org/doc/articles/race_detector.html) and fix any problems reported by the detector.

**Comment by di3663** [comment]
@garyburd 

Race detector found nothing, actually it's a simple class function test, there is no goroutines. 
After switch to go-redis, i found the similar error, instead go-redis hangs when reading from redis server rather than throw a deadlock error.

I alse tested the program on linux, there is no error. So I believe that maybe something's wrong with `net/net.go`, although redis server is running on windows, other language works.

**Comment by di3663** [comment]
It turns out that when trans an argument as string, it became empty string "", my fault, sorry for bothering you.
